// Ported from the original bunkei_kitchen.html prototype's STAGES array.
// Every example sentence is itself about cooking, so completing the sentence
// literally completes the dish it describes.
//
// Vocabulary level: all English sentences are restricted to words and
// grammar covered by the Japanese junior-high (中学3年生まで) curriculum.
export type Role = 'S' | 'V' | 'O' | 'O1' | 'O2' | 'C' | 'M';

export interface Chunk {
  t: string; // word / phrase text
  r: Role;
  e: string; // emoji icon
}

export interface Puzzle {
  jp: string;
  en: string;
  dish: string;
  chunks: Chunk[];
}

export interface Stage {
  key: string;
  emoji: string;
  name: string;
  pattern: string;
  desc: string;
  puzzles: Puzzle[];
}

export const STAGES: Stage[] = [
  {
    key: 'SV',
    emoji: '🍚',
    name: '下ごしらえ：食材が変わりだす',
    pattern: 'S + V',
    desc: '食材(S)が動詞(V)だけで変化していく、いちばんシンプルな調理。',
    puzzles: [
      { jp: '卵がゆでられる。', en: 'The egg boils.', dish: 'ゆで卵', chunks: [{ t: 'The egg', r: 'S', e: '🥚' }, { t: 'boils', r: 'V', e: '♨️' }] },
      { jp: 'パンが焼ける。', en: 'The bread bakes.', dish: '焼きたてパン', chunks: [{ t: 'The bread', r: 'S', e: '🍞' }, { t: 'bakes', r: 'V', e: '🔥' }] },
      { jp: 'ケーキがふくらむ。', en: 'The cake rises.', dish: 'ふわふわケーキ', chunks: [{ t: 'The cake', r: 'S', e: '🎂' }, { t: 'rises', r: 'V', e: '⬆️' }] },
      { jp: 'ご飯が炊ける。', en: 'The rice cooks.', dish: '白いご飯', chunks: [{ t: 'The rice', r: 'S', e: '🍚' }, { t: 'cooks', r: 'V', e: '🔥' }] },
      { jp: '玉ねぎが泣く。', en: 'The onion cries.', dish: 'たまねぎスープ', chunks: [{ t: 'The onion', r: 'S', e: '🧅' }, { t: 'cries', r: 'V', e: '😢' }] },
      { jp: 'スープが煮える。', en: 'The soup boils.', dish: 'あつあつスープ', chunks: [{ t: 'The soup', r: 'S', e: '🍲' }, { t: 'boils', r: 'V', e: '♨️' }] },
      { jp: 'バターがとける。', en: 'The butter melts.', dish: 'バタートースト', chunks: [{ t: 'The butter', r: 'S', e: '🧈' }, { t: 'melts', r: 'V', e: '💧' }] },
      { jp: 'チョコレートがとける。', en: 'The chocolate melts.', dish: 'チョコケーキ', chunks: [{ t: 'The chocolate', r: 'S', e: '🍫' }, { t: 'melts', r: 'V', e: '💧' }] },
      { jp: '魚が揚がる。', en: 'The fish fries.', dish: '揚げ魚', chunks: [{ t: 'The fish', r: 'S', e: '🐟' }, { t: 'fries', r: 'V', e: '🍳' }] },
      { jp: '鶏肉が焼ける。', en: 'The chicken cooks.', dish: '焼き鳥', chunks: [{ t: 'The chicken', r: 'S', e: '🍗' }, { t: 'cooks', r: 'V', e: '🔥' }] },
      { jp: 'ピザが焼ける。', en: 'The pizza bakes.', dish: 'あつあつピザ', chunks: [{ t: 'The pizza', r: 'S', e: '🍕' }, { t: 'bakes', r: 'V', e: '🔥' }] },
      { jp: 'クッキーが焦げる。', en: 'The cookies burn.', dish: '黒いクッキー', chunks: [{ t: 'The cookies', r: 'S', e: '🍪' }, { t: 'burn', r: 'V', e: '🔥' }] },
      { jp: '野菜が乾く。', en: 'The vegetables dry.', dish: '乾燥野菜', chunks: [{ t: 'The vegetables', r: 'S', e: '🥬' }, { t: 'dry', r: 'V', e: '☀️' }] },
      { jp: 'トマトが育つ。', en: 'The tomatoes grow.', dish: '赤いトマト', chunks: [{ t: 'The tomatoes', r: 'S', e: '🍅' }, { t: 'grow', r: 'V', e: '🌱' }] },
      { jp: 'タイマーが鳴る。', en: 'The timer rings.', dish: 'できたてクッキー', chunks: [{ t: 'The timer', r: 'S', e: '⏰' }, { t: 'rings', r: 'V', e: '🔔' }] },
      { jp: '生徒たちが待つ。', en: 'The students wait.', dish: '給食カレー', chunks: [{ t: 'The students', r: 'S', e: '🧑‍🎓' }, { t: 'wait', r: 'V', e: '⏳' }] },
      { jp: 'オーブンが止まる。', en: 'The oven stops.', dish: '出来立てパイ', chunks: [{ t: 'The oven', r: 'S', e: '🔥' }, { t: 'stops', r: 'V', e: '🛑' }] },
      { jp: 'クラスが食べる。', en: 'The class eats.', dish: '給食パン', chunks: [{ t: 'The class', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'eats', r: 'V', e: '🍽️' }] },
      { jp: 'シェフが味見する。', en: 'The chef tastes.', dish: 'きょうのスープ', chunks: [{ t: 'The chef', r: 'S', e: '👨‍🍳' }, { t: 'tastes', r: 'V', e: '👅' }] },
      { jp: '牛乳がわく。', en: 'The milk boils.', dish: 'ホットミルク', chunks: [{ t: 'The milk', r: 'S', e: '🥛' }, { t: 'boils', r: 'V', e: '♨️' }] },
    ],
  },
  {
    key: 'SVM',
    emoji: '🍚',
    name: '下ごしらえ＋：時間や場所を添えて',
    pattern: 'S + V + M',
    desc: 'いつ・どこで・どんなふうに(M)を添えると、同じ調理がもっと具体的に伝わるよ。',
    puzzles: [
      { jp: '父は毎日料理する。', en: 'The father cooks every day.', dish: '毎日のみそ汁', chunks: [{ t: 'The father', r: 'S', e: '👨' }, { t: 'cooks', r: 'V', e: '🍳' }, { t: 'every day', r: 'M', e: '📅' }] },
      { jp: '牛乳は毎朝わく。', en: 'The milk boils every morning.', dish: 'あたたかいミルク', chunks: [{ t: 'The milk', r: 'S', e: '🥛' }, { t: 'boils', r: 'V', e: '♨️' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '家族は毎晩食べる。', en: 'The family eats every night.', dish: '夜ごはん', chunks: [{ t: 'The family', r: 'S', e: '👪' }, { t: 'eats', r: 'V', e: '🍽️' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '玉ねぎはキッチンで泣く。', en: 'The onion cries in the kitchen.', dish: 'なみだの玉ねぎスープ', chunks: [{ t: 'The onion', r: 'S', e: '🧅' }, { t: 'cries', r: 'V', e: '😢' }, { t: 'in the kitchen', r: 'M', e: '🏠' }] },
      { jp: 'トマトは家で育つ。', en: 'The tomatoes grow at home.', dish: '家庭菜園トマト', chunks: [{ t: 'The tomatoes', r: 'S', e: '🍅' }, { t: 'grow', r: 'V', e: '🌱' }, { t: 'at home', r: 'M', e: '🏠' }] },
      { jp: '私たちはスプーンで食べる。', en: 'We eat with a spoon.', dish: '夜のスープ', chunks: [{ t: 'We', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'eat', r: 'V', e: '🍽️' }, { t: 'with a spoon', r: 'M', e: '🥄' }] },
      { jp: 'お湯は5分でわく。', en: 'The water boils in five minutes.', dish: 'あったかいお茶', chunks: [{ t: 'The water', r: 'S', e: '💧' }, { t: 'boils', r: 'V', e: '♨️' }, { t: 'in five minutes', r: 'M', e: '⏱️' }] },
      { jp: '米は10分で炊ける。', en: 'The rice cooks in ten minutes.', dish: 'ほかほかご飯', chunks: [{ t: 'The rice', r: 'S', e: '🍚' }, { t: 'cooks', r: 'V', e: '🔥' }, { t: 'in ten minutes', r: 'M', e: '⏱️' }] },
      { jp: '父は夕食前に待つ。', en: 'The father waits before dinner.', dish: '夕食前のサラダ', chunks: [{ t: 'The father', r: 'S', e: '👨' }, { t: 'waits', r: 'V', e: '⏳' }, { t: 'before dinner', r: 'M', e: '🕓' }] },
      { jp: '生徒は放課後に待つ。', en: 'The students wait after school.', dish: '放課後のおやつ', chunks: [{ t: 'The students', r: 'S', e: '🧑‍🎓' }, { t: 'wait', r: 'V', e: '⏳' }, { t: 'after school', r: 'M', e: '🏫' }] },
      { jp: 'オーブンは夕食後に止まる。', en: 'The oven stops after dinner.', dish: '夕食後のパイ', chunks: [{ t: 'The oven', r: 'S', e: '🔥' }, { t: 'stops', r: 'V', e: '🛑' }, { t: 'after dinner', r: 'M', e: '🌙' }] },
      { jp: 'クッキーはすぐに焦げる。', en: 'The cookies burn quickly.', dish: 'こげこげクッキー', chunks: [{ t: 'The cookies', r: 'S', e: '🍪' }, { t: 'burn', r: 'V', e: '🔥' }, { t: 'quickly', r: 'M', e: '⚡' }] },
      { jp: 'シェフは注意深く味見する。', en: 'The chef tastes carefully.', dish: 'きょうのカレー', chunks: [{ t: 'The chef', r: 'S', e: '👨‍🍳' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'carefully', r: 'M', e: '🔍' }] },
      { jp: 'ケーキはゆっくりふくらむ。', en: 'The cake rises slowly.', dish: 'まんまるケーキ', chunks: [{ t: 'The cake', r: 'S', e: '🎂' }, { t: 'rises', r: 'V', e: '⬆️' }, { t: 'slowly', r: 'M', e: '🐢' }] },
      { jp: '生徒たちは一緒に料理する。', en: 'The students cook together.', dish: '家庭科カレー', chunks: [{ t: 'The students', r: 'S', e: '🧑‍🎓' }, { t: 'cook', r: 'V', e: '🍳' }, { t: 'together', r: 'M', e: '🤝' }] },
      { jp: '私たちは食卓で食べる。', en: 'We eat at the table.', dish: '家族の夕食', chunks: [{ t: 'We', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'eat', r: 'V', e: '🍽️' }, { t: 'at the table', r: 'M', e: '🪑' }] },
      { jp: 'スープはコンロで煮える。', en: 'The soup cooks on the stove.', dish: 'あさごはんスープ', chunks: [{ t: 'The soup', r: 'S', e: '🍲' }, { t: 'cooks', r: 'V', e: '🔥' }, { t: 'on the stove', r: 'M', e: '🍳' }] },
      { jp: 'パンはオーブンで焼ける。', en: 'The bread bakes in the oven.', dish: 'こんがりパン', chunks: [{ t: 'The bread', r: 'S', e: '🍞' }, { t: 'bakes', r: 'V', e: '🔥' }, { t: 'in the oven', r: 'M', e: '🔥' }] },
      { jp: 'チキンは1時間で焼ける。', en: 'The chicken cooks for an hour.', dish: 'こんがりチキン', chunks: [{ t: 'The chicken', r: 'S', e: '🍗' }, { t: 'cooks', r: 'V', e: '🔥' }, { t: 'for an hour', r: 'M', e: '⏰' }] },
      { jp: 'タイマーは毎朝鳴る。', en: 'The timer rings every morning.', dish: '朝のアラーム', chunks: [{ t: 'The timer', r: 'S', e: '⏰' }, { t: 'rings', r: 'V', e: '🔔' }, { t: 'every morning', r: 'M', e: '🌅' }] },
    ],
  },
  {
    key: 'SVC',
    emoji: '🍜',
    name: '味見チェック：仕上がりの一皿',
    pattern: 'S + V + C',
    desc: '動詞のあとの言葉(C)が食材(S)の状態そのものを言い換える。S ＝ C の関係だよ。',
    puzzles: [
      { jp: 'そのスープはおいしい味がする。', en: 'The soup tastes good.', dish: '具だくさんスープ', chunks: [{ t: 'The soup', r: 'S', e: '🍲' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'good', r: 'C', e: '😋' }] },
      { jp: 'そのカレーはスパイシーなにおいがする。', en: 'The curry smells spicy.', dish: '辛口カレー', chunks: [{ t: 'The curry', r: 'S', e: '🍛' }, { t: 'smells', r: 'V', e: '👃' }, { t: 'spicy', r: 'C', e: '🌶️' }] },
      { jp: 'そのケーキはおいしそうに見える。', en: 'The cake looks delicious.', dish: 'いちごケーキ', chunks: [{ t: 'The cake', r: 'S', e: '🍰' }, { t: 'looks', r: 'V', e: '👀' }, { t: 'delicious', r: 'C', e: '😋' }] },
      { jp: 'そのパンはやわらかい感じがする。', en: 'The bread feels soft.', dish: 'ふわふわパン', chunks: [{ t: 'The bread', r: 'S', e: '🍞' }, { t: 'feels', r: 'V', e: '🤲' }, { t: 'soft', r: 'C', e: '☁️' }] },
      { jp: 'ご飯は冷たくなる。', en: 'The rice gets cold.', dish: '冷めたご飯', chunks: [{ t: 'The rice', r: 'S', e: '🍚' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'cold', r: 'C', e: '🥶' }] },
      { jp: 'そのチキンはしょっぱい味がする。', en: 'The chicken tastes salty.', dish: '焼きチキン', chunks: [{ t: 'The chicken', r: 'S', e: '🍗' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'salty', r: 'C', e: '🧂' }] },
      { jp: 'そのサラダは新鮮に見える。', en: 'The salad looks fresh.', dish: '野菜サラダ', chunks: [{ t: 'The salad', r: 'S', e: '🥗' }, { t: 'looks', r: 'V', e: '👀' }, { t: 'fresh', r: 'C', e: '🌿' }] },
      { jp: 'その紅茶はいいにおいがする。', en: 'The tea smells nice.', dish: 'あったかい紅茶', chunks: [{ t: 'The tea', r: 'S', e: '🍵' }, { t: 'smells', r: 'V', e: '👃' }, { t: 'nice', r: 'C', e: '😊' }] },
      { jp: 'そのピザはいいにおいがする。', en: 'The pizza smells good.', dish: 'チーズピザ', chunks: [{ t: 'The pizza', r: 'S', e: '🍕' }, { t: 'smells', r: 'V', e: '👃' }, { t: 'good', r: 'C', e: '😋' }] },
      { jp: 'そのサンドイッチはおいしそうに見える。', en: 'The sandwich looks tasty.', dish: 'たまごサンドイッチ', chunks: [{ t: 'The sandwich', r: 'S', e: '🥪' }, { t: 'looks', r: 'V', e: '👀' }, { t: 'tasty', r: 'C', e: '😋' }] },
      { jp: 'そのクッキーは甘い。', en: 'The cookies taste sweet.', dish: 'バタークッキー', chunks: [{ t: 'The cookies', r: 'S', e: '🍪' }, { t: 'taste', r: 'V', e: '👅' }, { t: 'sweet', r: 'C', e: '🍬' }] },
      { jp: 'そのりんごはすっぱい。', en: 'The apple tastes sour.', dish: '青りんご', chunks: [{ t: 'The apple', r: 'S', e: '🍎' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'sour', r: 'C', e: '😖' }] },
      { jp: 'そのバナナは茶色になる。', en: 'The banana turns brown.', dish: '熟したバナナ', chunks: [{ t: 'The banana', r: 'S', e: '🍌' }, { t: 'turns', r: 'V', e: '🔄' }, { t: 'brown', r: 'C', e: '🟤' }] },
      { jp: 'そのオレンジは甘い。', en: 'The orange tastes sweet.', dish: '甘いオレンジ', chunks: [{ t: 'The orange', r: 'S', e: '🍊' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'sweet', r: 'C', e: '🍬' }] },
      { jp: 'そのアイスクリームはやわらかくなる。', en: 'The ice cream gets soft.', dish: 'バニラアイス', chunks: [{ t: 'The ice cream', r: 'S', e: '🍦' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'soft', r: 'C', e: '☁️' }] },
      { jp: 'そのチョコレートはあたたかく感じる。', en: 'The chocolate feels warm.', dish: '板チョコレート', chunks: [{ t: 'The chocolate', r: 'S', e: '🍫' }, { t: 'feels', r: 'V', e: '🤲' }, { t: 'warm', r: 'C', e: '🌡️' }] },
      { jp: 'その麺はやわらかい感じがする。', en: 'The noodles feel soft.', dish: 'しょうゆラーメン', chunks: [{ t: 'The noodles', r: 'S', e: '🍜' }, { t: 'feel', r: 'V', e: '🤲' }, { t: 'soft', r: 'C', e: '☁️' }] },
      { jp: 'そのみそ汁はしょっぱい。', en: 'The miso soup tastes salty.', dish: 'とうふのみそ汁', chunks: [{ t: 'The miso soup', r: 'S', e: '🍲' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'salty', r: 'C', e: '🧂' }] },
      { jp: 'その天ぷらはあつく感じる。', en: 'The tempura feels hot.', dish: 'えび天ぷら', chunks: [{ t: 'The tempura', r: 'S', e: '🍤' }, { t: 'feels', r: 'V', e: '🤲' }, { t: 'hot', r: 'C', e: '🔥' }] },
      { jp: 'そのすしは新鮮に見える。', en: 'The sushi looks fresh.', dish: 'サーモンずし', chunks: [{ t: 'The sushi', r: 'S', e: '🍣' }, { t: 'looks', r: 'V', e: '👀' }, { t: 'fresh', r: 'C', e: '🌿' }] },
    ],
  },
  {
    key: 'SVCM',
    emoji: '🍜',
    name: '味見チェック＋：状況を添えて',
    pattern: 'S + V + C + M',
    desc: 'S＝Cの言い換えに、いつ・どこで(M)を添えて、変化の様子をもっと詳しく伝えよう。',
    puzzles: [
      { jp: 'スパゲッティは鍋の中でやわらかくなる。', en: 'The spaghetti gets soft in the pot.', dish: 'トマトスパゲッティ', chunks: [{ t: 'The spaghetti', r: 'S', e: '🍝' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'soft', r: 'C', e: '☁️' }, { t: 'in the pot', r: 'M', e: '🍲' }] },
      { jp: 'ハンバーグはコンロの上でいいにおいがする。', en: 'The hamburger smells good on the stove.', dish: 'てりやきハンバーグ', chunks: [{ t: 'The hamburger', r: 'S', e: '🍔' }, { t: 'smells', r: 'V', e: '👃' }, { t: 'good', r: 'C', e: '😋' }, { t: 'on the stove', r: 'M', e: '🍳' }] },
      { jp: 'その魚はテーブルで新鮮な味がする。', en: 'The fish tastes fresh at the table.', dish: '焼き魚', chunks: [{ t: 'The fish', r: 'S', e: '🐟' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'at the table', r: 'M', e: '🍽️' }] },
      { jp: '肉はオーブンの中で茶色になる。', en: 'The meat becomes brown in the oven.', dish: 'ローストミート', chunks: [{ t: 'The meat', r: 'S', e: '🥩' }, { t: 'becomes', r: 'V', e: '🔄' }, { t: 'brown', r: 'C', e: '🟤' }, { t: 'in the oven', r: 'M', e: '🔥' }] },
      { jp: 'たまごは10分でかたくなる。', en: 'The egg gets hard in ten minutes.', dish: 'ゆでたまご', chunks: [{ t: 'The egg', r: 'S', e: '🥚' }, { t: 'gets', r: 'V', e: '📈' }, { t: 'hard', r: 'C', e: '🪨' }, { t: 'in ten minutes', r: 'M', e: '⏲️' }] },
      { jp: '野菜は毎朝新鮮に見える。', en: 'The vegetables look fresh every morning.', dish: '朝どれ野菜', chunks: [{ t: 'The vegetables', r: 'S', e: '🥦' }, { t: 'look', r: 'V', e: '👀' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: 'くだものは放課後甘い味がする。', en: 'The fruit tastes sweet after school.', dish: 'フルーツもりあわせ', chunks: [{ t: 'The fruit', r: 'S', e: '🍇' }, { t: 'tastes', r: 'V', e: '👅' }, { t: 'sweet', r: 'C', e: '🍬' }, { t: 'after school', r: 'M', e: '🎒' }] },
      { jp: 'ジュースは冷蔵庫の中で冷たいままだ。', en: 'The juice stays cold in the fridge.', dish: 'りんごジュース', chunks: [{ t: 'The juice', r: 'S', e: '🧃' }, { t: 'stays', r: 'V', e: '🟰' }, { t: 'cold', r: 'C', e: '🥶' }, { t: 'in the fridge', r: 'M', e: '🧊' }] },
      { jp: 'ラーメンはすぐに冷める。', en: 'The ramen gets cold quickly.', dish: 'とんこつラーメン', chunks: [{ t: 'The ramen', r: 'S', e: '🍜' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'cold', r: 'C', e: '🥶' }, { t: 'quickly', r: 'M', e: '⚡' }] },
      { jp: 'おにぎりは冷蔵庫の中で新鮮なままだ。', en: 'The onigiri stays fresh in the fridge.', dish: '梅おにぎり', chunks: [{ t: 'The onigiri', r: 'S', e: '🍙' }, { t: 'stays', r: 'V', e: '🟰' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'in the fridge', r: 'M', e: '🧊' }] },
      { jp: 'じゃがいもはオーブンの中でやわらかくなる。', en: 'The potato becomes soft in the oven.', dish: 'ベイクドポテト', chunks: [{ t: 'The potato', r: 'S', e: '🥔' }, { t: 'becomes', r: 'V', e: '🔄' }, { t: 'soft', r: 'C', e: '☁️' }, { t: 'in the oven', r: 'M', e: '🔥' }] },
      { jp: 'トマトはもうすぐ赤くなる。', en: 'The tomato turns red soon.', dish: 'まるごとトマト', chunks: [{ t: 'The tomato', r: 'S', e: '🍅' }, { t: 'turns', r: 'V', e: '🔄' }, { t: 'red', r: 'C', e: '🔴' }, { t: 'soon', r: 'M', e: '⏳' }] },
      { jp: '玉ねぎはゆっくり茶色になる。', en: 'The onion turns brown slowly.', dish: 'あめ色オニオン', chunks: [{ t: 'The onion', r: 'S', e: '🧅' }, { t: 'turns', r: 'V', e: '🔄' }, { t: 'brown', r: 'C', e: '🟤' }, { t: 'slowly', r: 'M', e: '🐢' }] },
      { jp: 'にんじんは5分でやわらかくなる。', en: 'The carrot becomes soft in five minutes.', dish: 'グラッセにんじん', chunks: [{ t: 'The carrot', r: 'S', e: '🥕' }, { t: 'becomes', r: 'V', e: '🔄' }, { t: 'soft', r: 'C', e: '☁️' }, { t: 'in five minutes', r: 'M', e: '⏲️' }] },
      { jp: 'バターは夕食前にやわらかくなる。', en: 'The butter gets soft before dinner.', dish: 'やわらかバター', chunks: [{ t: 'The butter', r: 'S', e: '🧈' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'soft', r: 'C', e: '☁️' }, { t: 'before dinner', r: 'M', e: '🍽️' }] },
      { jp: 'チーズは台所でいいにおいがする。', en: 'The cheese smells good in the kitchen.', dish: 'チーズトースト', chunks: [{ t: 'The cheese', r: 'S', e: '🧀' }, { t: 'smells', r: 'V', e: '👃' }, { t: 'good', r: 'C', e: '😋' }, { t: 'in the kitchen', r: 'M', e: '🏠' }] },
      { jp: '水はコンロの上であつくなる。', en: 'The water gets hot on the stove.', dish: 'あついお湯', chunks: [{ t: 'The water', r: 'S', e: '💧' }, { t: 'gets', r: 'V', e: '📈' }, { t: 'hot', r: 'C', e: '🔥' }, { t: 'on the stove', r: 'M', e: '🍳' }] },
      { jp: '砂糖は台所でかわいたままだ。', en: 'The sugar stays dry in the kitchen.', dish: 'グラニュー糖', chunks: [{ t: 'The sugar', r: 'S', e: '🥄' }, { t: 'stays', r: 'V', e: '🟰' }, { t: 'dry', r: 'C', e: '🏜️' }, { t: 'in the kitchen', r: 'M', e: '🏠' }] },
      { jp: '塩はなべの中でかわいた感じがする。', en: 'The salt feels dry in the pot.', dish: 'あら塩', chunks: [{ t: 'The salt', r: 'S', e: '🧂' }, { t: 'feels', r: 'V', e: '🤲' }, { t: 'dry', r: 'C', e: '🏜️' }, { t: 'in the pot', r: 'M', e: '🍲' }] },
      { jp: '牛乳は冷蔵庫の中で冷たくなる。', en: 'The milk gets cold in the fridge.', dish: 'つめたい牛乳', chunks: [{ t: 'The milk', r: 'S', e: '🥛' }, { t: 'gets', r: 'V', e: '📉' }, { t: 'cold', r: 'C', e: '🥶' }, { t: 'in the fridge', r: 'M', e: '🧊' }] },
    ],
  },
  {
    key: 'SVO',
    emoji: '🍳',
    name: 'メイン：具材を加える一皿',
    pattern: 'S + V + O',
    desc: '調理する人(S)が具材(O)を１つ加える、基本の組み立て。',
    puzzles: [
      { jp: '私は野菜を切る。', en: 'I cut vegetables.', dish: '野菜カット', chunks: [{ t: 'I', r: 'S', e: '🧑‍🍳' }, { t: 'cut', r: 'V', e: '🔪' }, { t: 'vegetables', r: 'O', e: '🥦' }] },
      { jp: '彼はご飯を炊く。', en: 'He cooks rice.', dish: '炊きたてご飯', chunks: [{ t: 'He', r: 'S', e: '👦' }, { t: 'cooks', r: 'V', e: '🍳' }, { t: 'rice', r: 'O', e: '🍚' }] },
      { jp: '彼女はサンドイッチを作る。', en: 'She makes a sandwich.', dish: '手作りサンドイッチ', chunks: [{ t: 'She', r: 'S', e: '👧' }, { t: 'makes', r: 'V', e: '👩‍🍳' }, { t: 'a sandwich', r: 'O', e: '🥪' }] },
      { jp: '私たちは卵をゆでる。', en: 'We boil eggs.', dish: 'ボイルドエッグ', chunks: [{ t: 'We', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'boil', r: 'V', e: '♨️' }, { t: 'eggs', r: 'O', e: '🥚' }] },
      { jp: '彼らは魚を焼く。', en: 'They fry fish.', dish: '焼き魚定食', chunks: [{ t: 'They', r: 'S', e: '👥' }, { t: 'fry', r: 'V', e: '🍳' }, { t: 'fish', r: 'O', e: '🐟' }] },
      { jp: '母はケーキを焼く。', en: 'My mother bakes a cake.', dish: 'バースデーケーキ', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'bakes', r: 'V', e: '🎂' }, { t: 'a cake', r: 'O', e: '🍰' }] },
      { jp: '父はサラダを混ぜる。', en: 'My father mixes salad.', dish: 'ミックスサラダ', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'mixes', r: 'V', e: '🥣' }, { t: 'salad', r: 'O', e: '🥗' }] },
      { jp: 'シェフはチーズを加える。', en: 'The chef adds cheese.', dish: 'チーズのせトースト', chunks: [{ t: 'The chef', r: 'S', e: '👨‍🍳' }, { t: 'adds', r: 'V', e: '➕' }, { t: 'cheese', r: 'O', e: '🧀' }] },
      { jp: '生徒たちはじゃがいもを洗う。', en: 'The students wash potatoes.', dish: '洗いじゃがいも', chunks: [{ t: 'The students', r: 'S', e: '🧑‍🎓' }, { t: 'wash', r: 'V', e: '🚿' }, { t: 'potatoes', r: 'O', e: '🥔' }] },
      { jp: 'トムはりんごを買う。', en: 'Tom buys apples.', dish: '新鮮なりんご', chunks: [{ t: 'Tom', r: 'S', e: '👦' }, { t: 'buys', r: 'V', e: '🛒' }, { t: 'apples', r: 'O', e: '🍎' }] },
      { jp: 'マリアはピザを運ぶ。', en: 'Maria carries a pizza.', dish: '宅配ピザ', chunks: [{ t: 'Maria', r: 'S', e: '👩' }, { t: 'carries', r: 'V', e: '🚚' }, { t: 'a pizza', r: 'O', e: '🍕' }] },
      { jp: '料理人はトマトを洗う。', en: 'The cook cleans the tomatoes.', dish: '冷製トマト', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'cleans', r: 'V', e: '🧼' }, { t: 'the tomatoes', r: 'O', e: '🍅' }] },
      { jp: '妹はアイスクリームが欲しい。', en: 'My sister wants ice cream.', dish: 'つめたいアイス', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'wants', r: 'V', e: '💭' }, { t: 'ice cream', r: 'O', e: '🍨' }] },
      { jp: '兄はバナナを食べる。', en: 'My brother eats a banana.', dish: 'バナナおやつ', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'eats', r: 'V', e: '🍽️' }, { t: 'a banana', r: 'O', e: '🍌' }] },
      { jp: '男の子はジュースを飲む。', en: 'The boy drinks juice.', dish: 'オレンジジュース', chunks: [{ t: 'The boy', r: 'S', e: '👦' }, { t: 'drinks', r: 'V', e: '🥤' }, { t: 'juice', r: 'O', e: '🧃' }] },
      { jp: '女の子はバターが必要だ。', en: 'The girl needs butter.', dish: 'バターぬりパン', chunks: [{ t: 'The girl', r: 'S', e: '👧' }, { t: 'needs', r: 'V', e: '❗' }, { t: 'butter', r: 'O', e: '🧈' }] },
      { jp: '私はチョコレートが好きだ。', en: 'I like chocolate.', dish: 'チョコレート菓子', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'like', r: 'V', e: '❤️' }, { t: 'chocolate', r: 'O', e: '🍫' }] },
      { jp: '彼はたまねぎを切る。', en: 'He cuts onions.', dish: 'オニオンスライス', chunks: [{ t: 'He', r: 'S', e: '👨' }, { t: 'cuts', r: 'V', e: '🔪' }, { t: 'onions', r: 'O', e: '🧅' }] },
      { jp: '彼女は魚を捕る。', en: 'She catches fish.', dish: '釣りたての魚', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'catches', r: 'V', e: '🎣' }, { t: 'fish', r: 'O', e: '🐟' }] },
      { jp: '彼らはラーメンを売る。', en: 'They sell ramen.', dish: '屋台ラーメン', chunks: [{ t: 'They', r: 'S', e: '👥' }, { t: 'sell', r: 'V', e: '💴' }, { t: 'ramen', r: 'O', e: '🍜' }] },
    ],
  },
  {
    key: 'SVOM',
    emoji: '🍳',
    name: 'メイン＋：ひと工夫を添えて',
    pattern: 'S + V + O + M',
    desc: '具材(O)を加える動作に、どんなふうに・いつ(M)を添えて、もっと丁寧に仕上げよう。',
    puzzles: [
      { jp: '私は毎朝卵を焼く。', en: 'I fry an egg every morning.', dish: '目玉焼き', chunks: [{ t: 'I', r: 'S', e: '🧑‍🍳' }, { t: 'fry', r: 'V', e: '🍳' }, { t: 'an egg', r: 'O', e: '🥚' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '彼は放課後にカレーを作る。', en: 'He makes curry after school.', dish: '放課後カレー', chunks: [{ t: 'He', r: 'S', e: '👦' }, { t: 'makes', r: 'V', e: '👨‍🍳' }, { t: 'curry', r: 'O', e: '🍛' }, { t: 'after school', r: 'M', e: '🎒' }] },
      { jp: '彼女はオーブンでクッキーを焼く。', en: 'She bakes cookies in the oven.', dish: '手作りクッキー', chunks: [{ t: 'She', r: 'S', e: '👧' }, { t: 'bakes', r: 'V', e: '🎂' }, { t: 'cookies', r: 'O', e: '🍪' }, { t: 'in the oven', r: 'M', e: '🔥' }] },
      { jp: '私たちは毎日ご飯を炊く。', en: 'We cook rice every day.', dish: '毎日のご飯', chunks: [{ t: 'We', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'cook', r: 'V', e: '🍳' }, { t: 'rice', r: 'O', e: '🍚' }, { t: 'every day', r: 'M', e: '📅' }] },
      { jp: '彼らは夕食前に野菜を洗う。', en: 'They wash vegetables before dinner.', dish: '夕食前の野菜', chunks: [{ t: 'They', r: 'S', e: '👥' }, { t: 'wash', r: 'V', e: '🚿' }, { t: 'vegetables', r: 'O', e: '🥦' }, { t: 'before dinner', r: 'M', e: '🕕' }] },
      { jp: '母は家でスープを作る。', en: 'My mother makes soup at home.', dish: '家庭のスープ', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '👩‍🍳' }, { t: 'soup', r: 'O', e: '🍲' }, { t: 'at home', r: 'M', e: '🏠' }] },
      { jp: '父はじゃがいもを1時間ゆでる。', en: 'My father boils potatoes for an hour.', dish: 'ほくほくポテト', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'boils', r: 'V', e: '♨️' }, { t: 'potatoes', r: 'O', e: '🥔' }, { t: 'for an hour', r: 'M', e: '⏰' }] },
      { jp: 'シェフはナイフでたまねぎを切る。', en: 'The chef cuts onions with a knife.', dish: 'ナイフ使いのオニオン', chunks: [{ t: 'The chef', r: 'S', e: '👨‍🍳' }, { t: 'cuts', r: 'V', e: '🔪' }, { t: 'onions', r: 'O', e: '🧅' }, { t: 'with a knife', r: 'M', e: '🔪' }] },
      { jp: '生徒たちは一緒に昼食を食べる。', en: 'The students eat lunch together.', dish: 'みんなの給食', chunks: [{ t: 'The students', r: 'S', e: '🧑‍🎓' }, { t: 'eat', r: 'V', e: '🍽️' }, { t: 'lunch', r: 'O', e: '🍱' }, { t: 'together', r: 'M', e: '🤝' }] },
      { jp: 'トムは慎重にピザを運ぶ。', en: 'Tom carries the pizza carefully.', dish: '慎重ピザ', chunks: [{ t: 'Tom', r: 'S', e: '👦' }, { t: 'carries', r: 'V', e: '🚚' }, { t: 'the pizza', r: 'O', e: '🍕' }, { t: 'carefully', r: 'M', e: '🧐' }] },
      { jp: 'マリアはスプーンでサラダを混ぜる。', en: 'Maria mixes the salad with a spoon.', dish: 'スプーン仕込みサラダ', chunks: [{ t: 'Maria', r: 'S', e: '👩' }, { t: 'mixes', r: 'V', e: '🥄' }, { t: 'the salad', r: 'O', e: '🥗' }, { t: 'with a spoon', r: 'M', e: '🥄' }] },
      { jp: '料理人はゆっくりチーズを加える。', en: 'The cook adds cheese slowly.', dish: 'とろけるチーズ', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'adds', r: 'V', e: '➕' }, { t: 'cheese', r: 'O', e: '🧀' }, { t: 'slowly', r: 'M', e: '🐢' }] },
      { jp: '妹はすばやくバナナを買う。', en: 'My sister buys bananas quickly.', dish: '特売バナナ', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'buys', r: 'V', e: '🛒' }, { t: 'bananas', r: 'O', e: '🍌' }, { t: 'quickly', r: 'M', e: '⚡' }] },
      { jp: '兄は毎晩牛乳を飲む。', en: 'My brother drinks milk every night.', dish: 'おやすみミルク', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'drinks', r: 'V', e: '🥛' }, { t: 'milk', r: 'O', e: '🥛' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '男の子はテーブルでラーメンを食べる。', en: 'The boy eats noodles at the table.', dish: '家族の麺', chunks: [{ t: 'The boy', r: 'S', e: '👦' }, { t: 'eats', r: 'V', e: '🍽️' }, { t: 'noodles', r: 'O', e: '🍜' }, { t: 'at the table', r: 'M', e: '🍽️' }] },
      { jp: '女の子は台所でパンを焼く。', en: 'The girl bakes bread in the kitchen.', dish: '台所の焼きたてパン', chunks: [{ t: 'The girl', r: 'S', e: '👧' }, { t: 'bakes', r: 'V', e: '🍞' }, { t: 'bread', r: 'O', e: '🍞' }, { t: 'in the kitchen', r: 'M', e: '🍳' }] },
      { jp: '私はコンロで鶏肉を料理する。', en: 'I cook chicken on the stove.', dish: 'コンロ焼き鶏肉', chunks: [{ t: 'I', r: 'S', e: '🧑‍🍳' }, { t: 'cook', r: 'V', e: '🍳' }, { t: 'chicken', r: 'O', e: '🍗' }, { t: 'on the stove', r: 'M', e: '🔥' }] },
      { jp: '彼は10分でオレンジを買う。', en: 'He buys oranges in ten minutes.', dish: '急ぎのオレンジ', chunks: [{ t: 'He', r: 'S', e: '👨' }, { t: 'buys', r: 'V', e: '🛒' }, { t: 'oranges', r: 'O', e: '🍊' }, { t: 'in ten minutes', r: 'M', e: '⏱️' }] },
      { jp: '彼女は5分でお茶を入れる。', en: 'She makes tea in five minutes.', dish: '5分紅茶', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🍵' }, { t: 'tea', r: 'O', e: '🍵' }, { t: 'in five minutes', r: 'M', e: '⏱️' }] },
      { jp: '私たちは夕食後にピザが欲しい。', en: 'We want pizza after dinner.', dish: '夜食ピザ', chunks: [{ t: 'We', r: 'S', e: '🧑‍🤝‍🧑' }, { t: 'want', r: 'V', e: '💭' }, { t: 'pizza', r: 'O', e: '🍕' }, { t: 'after dinner', r: 'M', e: '🌙' }] },
    ],
  },
  {
    key: 'SVOO',
    emoji: '🍱',
    name: 'おもてなし：二品盛り合わせ',
    pattern: 'S + V + O1 + O2',
    desc: '「誰に(O1)」「何を(O2)」を、シェフ(S)が一気に振る舞うおもてなし料理。',
    puzzles: [
      { jp: '母は私におにぎりを作ってくれる。', en: 'My mother makes me a rice ball.', dish: 'おにぎり', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🍙' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'a rice ball', r: 'O2', e: '🍙' }] },
      { jp: '彼は彼女にチョコレートをあげる。', en: 'He gives her chocolate.', dish: 'チョコレート', chunks: [{ t: 'He', r: 'S', e: '🧑' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'her', r: 'O1', e: '👩' }, { t: 'chocolate', r: 'O2', e: '🍫' }] },
      { jp: '彼女は彼にハンバーガーを買ってあげる。', en: 'She buys him a hamburger.', dish: 'ハンバーガー', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'buys', r: 'V', e: '🛒' }, { t: 'him', r: 'O1', e: '🧑' }, { t: 'a hamburger', r: 'O2', e: '🍔' }] },
      { jp: '私たちは彼らにクッキーを持っていく。', en: 'We bring them cookies.', dish: 'クッキー', chunks: [{ t: 'We', r: 'S', e: '👥' }, { t: 'bring', r: 'V', e: '🚶' }, { t: 'them', r: 'O1', e: '👫' }, { t: 'cookies', r: 'O2', e: '🍪' }] },
      { jp: '彼らは私たちにカレーを作ってくれる。', en: 'They cook us curry.', dish: 'カレーライス', chunks: [{ t: 'They', r: 'S', e: '👫' }, { t: 'cook', r: 'V', e: '🍳' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'curry', r: 'O2', e: '🍛' }] },
      { jp: '父は私に牛乳を注いでくれる。', en: 'My father pours me milk.', dish: 'ミルク', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'pours', r: 'V', e: '🫗' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'milk', r: 'O2', e: '🥛' }] },
      { jp: 'コックは私たちにスープを出してくれる。', en: 'The cook sends us soup.', dish: 'やさいスープ', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'sends', r: 'V', e: '📨' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'soup', r: 'O2', e: '🍲' }] },
      { jp: '祖母は私にたまごを取ってくれる。', en: 'My grandmother gets me an egg.', dish: 'とりたてたまご', chunks: [{ t: 'My grandmother', r: 'S', e: '👵' }, { t: 'gets', r: 'V', e: '🥚' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'an egg', r: 'O2', e: '🥚' }] },
      { jp: '先生は生徒たちにピザを見つけてあげる。', en: 'The teacher finds the students pizza.', dish: 'ピザ', chunks: [{ t: 'The teacher', r: 'S', e: '👩‍🏫' }, { t: 'finds', r: 'V', e: '🔍' }, { t: 'the students', r: 'O1', e: '🧑‍🎓' }, { t: 'pizza', r: 'O2', e: '🍕' }] },
      { jp: 'ウェイターは彼らにアイスクリームを売る。', en: 'The waiter sells them ice cream.', dish: 'アイスクリーム', chunks: [{ t: 'The waiter', r: 'S', e: '🧑‍🍳' }, { t: 'sells', r: 'V', e: '💰' }, { t: 'them', r: 'O1', e: '👫' }, { t: 'ice cream', r: 'O2', e: '🍨' }] },
      { jp: 'トムはマリアにパンを渡す。', en: 'Tom passes Maria bread.', dish: 'パン', chunks: [{ t: 'Tom', r: 'S', e: '🧑' }, { t: 'passes', r: 'V', e: '🤝' }, { t: 'Maria', r: 'O1', e: '👩' }, { t: 'bread', r: 'O2', e: '🍞' }] },
      { jp: 'マリアはトムにメニューを見せる。', en: 'Maria shows Tom the menu.', dish: 'メニュー', chunks: [{ t: 'Maria', r: 'S', e: '👩' }, { t: 'shows', r: 'V', e: '📋' }, { t: 'Tom', r: 'O1', e: '🧑' }, { t: 'the menu', r: 'O2', e: '📋' }] },
      { jp: '母は私たちにレシピを教えてくれる。', en: 'My mother teaches us the recipe.', dish: 'レシピ', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'teaches', r: 'V', e: '📖' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'the recipe', r: 'O2', e: '📝' }] },
      { jp: '姉は私にお話をしてくれる。', en: 'My sister tells me a story.', dish: 'おはなし', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'tells', r: 'V', e: '💬' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'a story', r: 'O2', e: '📖' }] },
      { jp: '兄は子どもたちにジュースをあげる。', en: 'My brother gives the children juice.', dish: 'ジュース', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'the children', r: 'O1', e: '🧒' }, { t: 'juice', r: 'O2', e: '🧃' }] },
      { jp: '私は友達にめんを作ってあげる。', en: 'I make my friend noodles.', dish: 'やきそば', chunks: [{ t: 'I', r: 'S', e: '🙋' }, { t: 'make', r: 'V', e: '🍳' }, { t: 'my friend', r: 'O1', e: '🧑' }, { t: 'noodles', r: 'O2', e: '🍜' }] },
      { jp: '私たちは彼女にりんごを買ってあげる。', en: 'We buy her an apple.', dish: 'りんご', chunks: [{ t: 'We', r: 'S', e: '👥' }, { t: 'buy', r: 'V', e: '🛒' }, { t: 'her', r: 'O1', e: '👩' }, { t: 'an apple', r: 'O2', e: '🍎' }] },
      { jp: '彼らは私たちにバナナを持ってきてくれる。', en: 'They bring us a banana.', dish: 'バナナ', chunks: [{ t: 'They', r: 'S', e: '👫' }, { t: 'bring', r: 'V', e: '🚶' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'a banana', r: 'O2', e: '🍌' }] },
      { jp: '父は母にお茶をあげる。', en: 'My father gives my mother tea.', dish: '緑茶', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'my mother', r: 'O1', e: '👩' }, { t: 'tea', r: 'O2', e: '🍵' }] },
      { jp: 'コックは子どもたちに魚を料理してあげる。', en: 'The cook cooks the children fish.', dish: 'にこみ魚', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'cooks', r: 'V', e: '🍳' }, { t: 'the children', r: 'O1', e: '🧒' }, { t: 'fish', r: 'O2', e: '🐟' }] },
    ],
  },
  {
    key: 'SVOOM',
    emoji: '🍱',
    name: 'おもてなし＋：心遣いを添えて',
    pattern: 'S + V + O1 + O2 + M',
    desc: 'おもてなしの一皿に、いつ・どんな気持ちで(M)を添えて、もっと丁寧にふるまおう。',
    puzzles: [
      { jp: '母は毎朝私にお茶を入れてくれる。', en: 'My mother makes me tea every morning.', dish: '紅茶', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🍵' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'tea', r: 'O2', e: '🍵' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '彼はパーティーで私たちにケーキをくれる。', en: 'He gives us cake at the party.', dish: 'パーティーケーキ', chunks: [{ t: 'He', r: 'S', e: '🧑' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'cake', r: 'O2', e: '🍰' }, { t: 'at the party', r: 'M', e: '🎉' }] },
      { jp: '彼女は放課後、彼にサンドイッチを買ってあげる。', en: 'She buys him a sandwich after school.', dish: 'ハムサンド', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'buys', r: 'V', e: '🛒' }, { t: 'him', r: 'O1', e: '🧑' }, { t: 'a sandwich', r: 'O2', e: '🥪' }, { t: 'after school', r: 'M', e: '🏫' }] },
      { jp: '私たちは毎晩彼らにごはんを作ってあげる。', en: 'We cook them rice every night.', dish: '白ごはん', chunks: [{ t: 'We', r: 'S', e: '👥' }, { t: 'cook', r: 'V', e: '🍳' }, { t: 'them', r: 'O1', e: '👫' }, { t: 'rice', r: 'O2', e: '🍚' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '彼らは毎週末、彼女に野菜を持ってくる。', en: 'They bring her vegetables every weekend.', dish: 'やさいサラダ', chunks: [{ t: 'They', r: 'S', e: '👫' }, { t: 'bring', r: 'V', e: '🚶' }, { t: 'her', r: 'O1', e: '👩' }, { t: 'vegetables', r: 'O2', e: '🥦' }, { t: 'every weekend', r: 'M', e: '📅' }] },
      { jp: '父は毎朝私にたまごを取ってくれる。', en: 'My father gets me an egg every morning.', dish: '卵焼き', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'gets', r: 'V', e: '🥚' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'an egg', r: 'O2', e: '🥚' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: 'コックは夕食前に私たちにスープを出してくれる。', en: 'The cook sends us soup before dinner.', dish: 'コーンスープ', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'sends', r: 'V', e: '📨' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'soup', r: 'O2', e: '🍲' }, { t: 'before dinner', r: 'M', e: '🍽️' }] },
      { jp: '祖母は夕食後、私たちに牛乳を注いでくれる。', en: 'My grandmother pours us milk after dinner.', dish: '牧場ミルク', chunks: [{ t: 'My grandmother', r: 'S', e: '👵' }, { t: 'pours', r: 'V', e: '🫗' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'milk', r: 'O2', e: '🥛' }, { t: 'after dinner', r: 'M', e: '🍽️' }] },
      { jp: '先生は学校で生徒たちにチョコレートをあげる。', en: 'The teacher gives the students chocolate at school.', dish: 'チョコレートケーキ', chunks: [{ t: 'The teacher', r: 'S', e: '👩‍🏫' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'the students', r: 'O1', e: '🧑‍🎓' }, { t: 'chocolate', r: 'O2', e: '🍫' }, { t: 'at school', r: 'M', e: '🏫' }] },
      { jp: 'ウェイターはパーティーで彼らにピザを持ってくる。', en: 'The waiter brings them pizza at the party.', dish: 'ピザトースト', chunks: [{ t: 'The waiter', r: 'S', e: '🧑‍🍳' }, { t: 'brings', r: 'V', e: '🚶' }, { t: 'them', r: 'O1', e: '👫' }, { t: 'pizza', r: 'O2', e: '🍕' }, { t: 'at the party', r: 'M', e: '🎉' }] },
      { jp: 'トムはすばやくマリアにサラダを渡す。', en: 'Tom passes Maria salad quickly.', dish: 'グリーンサラダ', chunks: [{ t: 'Tom', r: 'S', e: '🧑' }, { t: 'passes', r: 'V', e: '🤝' }, { t: 'Maria', r: 'O1', e: '👩' }, { t: 'salad', r: 'O2', e: '🥗' }, { t: 'quickly', r: 'M', e: '💨' }] },
      { jp: 'マリアは学校でトムにメニューを見せる。', en: 'Maria shows Tom the menu at school.', dish: 'きゅうしょくメニュー', chunks: [{ t: 'Maria', r: 'S', e: '👩' }, { t: 'shows', r: 'V', e: '📋' }, { t: 'Tom', r: 'O1', e: '🧑' }, { t: 'the menu', r: 'O2', e: '📋' }, { t: 'at school', r: 'M', e: '🏫' }] },
      { jp: '母は毎週末、私たちにレシピを教えてくれる。', en: 'My mother teaches us the recipe every weekend.', dish: 'おかしのレシピ', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'teaches', r: 'V', e: '📖' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'the recipe', r: 'O2', e: '📝' }, { t: 'every weekend', r: 'M', e: '📅' }] },
      { jp: '姉は毎晩私にお話をしてくれる。', en: 'My sister tells me a story every night.', dish: 'おやすみばなし', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'tells', r: 'V', e: '💬' }, { t: 'me', r: 'O1', e: '🙋' }, { t: 'a story', r: 'O2', e: '📖' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '兄は朝、子どもたちにジュースをあげる。', en: 'My brother gives the children juice in the morning.', dish: 'あさのりんごジュース', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'the children', r: 'O1', e: '🧒' }, { t: 'juice', r: 'O2', e: '🧃' }, { t: 'in the morning', r: 'M', e: '🌄' }] },
      { jp: '私は毎日午後、友達にめんを作ってあげる。', en: 'I make my friend noodles every afternoon.', dish: 'みそラーメン', chunks: [{ t: 'I', r: 'S', e: '🙋' }, { t: 'make', r: 'V', e: '🍳' }, { t: 'my friend', r: 'O1', e: '🧑' }, { t: 'noodles', r: 'O2', e: '🍜' }, { t: 'every afternoon', r: 'M', e: '☀️' }] },
      { jp: '私たちは夕食前に彼女にりんごを買ってあげる。', en: 'We buy her an apple before dinner.', dish: '焼きりんご', chunks: [{ t: 'We', r: 'S', e: '👥' }, { t: 'buy', r: 'V', e: '🛒' }, { t: 'her', r: 'O1', e: '👩' }, { t: 'an apple', r: 'O2', e: '🍎' }, { t: 'before dinner', r: 'M', e: '🍽️' }] },
      { jp: '彼らは毎日私たちにバナナを持ってきてくれる。', en: 'They bring us a banana every day.', dish: 'バナナケーキ', chunks: [{ t: 'They', r: 'S', e: '👫' }, { t: 'bring', r: 'V', e: '🚶' }, { t: 'us', r: 'O1', e: '👥' }, { t: 'a banana', r: 'O2', e: '🍌' }, { t: 'every day', r: 'M', e: '📆' }] },
      { jp: '父は家で母にお茶をあげる。', en: 'My father gives my mother tea at home.', dish: 'ミルクティー', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'gives', r: 'V', e: '🎁' }, { t: 'my mother', r: 'O1', e: '👩' }, { t: 'tea', r: 'O2', e: '🍵' }, { t: 'at home', r: 'M', e: '🏠' }] },
      { jp: 'コックは日曜日に子どもたちに魚を料理してあげる。', en: 'The cook cooks the children fish on Sundays.', dish: 'さかなフライ', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'cooks', r: 'V', e: '🍳' }, { t: 'the children', r: 'O1', e: '🧒' }, { t: 'fish', r: 'O2', e: '🐟' }, { t: 'on Sundays', r: 'M', e: '⛪' }] },
    ],
  },
  {
    key: 'SVOC',
    emoji: '🔥',
    name: '変化球メニュー：ひと手間の一皿',
    pattern: 'S + V + O + C',
    desc: '火加減(S)がひと手間で具材(O)を(C)の状態に変える、上級コース。O ＝ C の関係だよ。',
    puzzles: [
      { jp: '砂糖がケーキを甘くする。', en: 'Sugar makes the cake sweet.', dish: 'あまいケーキ', chunks: [{ t: 'Sugar', r: 'S', e: '🧂' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the cake', r: 'O', e: '🍰' }, { t: 'sweet', r: 'C', e: '🍬' }] },
      { jp: '熱がスープを熱くする。', en: 'Heat makes the soup hot.', dish: 'ぽかぽかスープ', chunks: [{ t: 'Heat', r: 'S', e: '🔥' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'hot', r: 'C', e: '♨️' }] },
      { jp: 'オーブンがパンを茶色にする。', en: 'The oven makes the bread brown.', dish: 'きつね色パン', chunks: [{ t: 'The oven', r: 'S', e: '🔥' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the bread', r: 'O', e: '🍞' }, { t: 'brown', r: 'C', e: '🟤' }] },
      { jp: '太陽が水をあたたかくする。', en: 'The sun makes the water warm.', dish: 'あたたかいお湯', chunks: [{ t: 'The sun', r: 'S', e: '☀️' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the water', r: 'O', e: '💧' }, { t: 'warm', r: 'C', e: '🌡️' }] },
      { jp: 'レモン汁がお茶をすっぱくする。', en: 'Lemon juice makes the tea sour.', dish: 'すっぱいレモンティー', chunks: [{ t: 'Lemon juice', r: 'S', e: '🍋' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the tea', r: 'O', e: '🍵' }, { t: 'sour', r: 'C', e: '😖' }] },
      { jp: '父は野菜を新鮮に保つ。', en: 'My father keeps the vegetables fresh.', dish: 'しんせんな野菜', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the vegetables', r: 'O', e: '🥦' }, { t: 'fresh', r: 'C', e: '🌿' }] },
      { jp: '料理人はパンをやわらかく保つ。', en: 'The cook keeps the bread soft.', dish: 'やわらかいパン', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the bread', r: 'O', e: '🍞' }, { t: 'soft', r: 'C', e: '☁️' }] },
      { jp: 'スパイスがカレーを辛くする。', en: 'Spice makes the curry spicy.', dish: 'からいカレー', chunks: [{ t: 'Spice', r: 'S', e: '🌶️' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the curry', r: 'O', e: '🍛' }, { t: 'spicy', r: 'C', e: '🔥' }] },
      { jp: '冷蔵庫がお茶を冷たくする。', en: 'The refrigerator makes the tea cold.', dish: 'つめたいお茶', chunks: [{ t: 'The refrigerator', r: 'S', e: '🧊' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the tea', r: 'O', e: '🍵' }, { t: 'cold', r: 'C', e: '❄️' }] },
      { jp: '私たちはそのスープを昼食と呼ぶ。', en: 'We call the soup lunch.', dish: 'ランチスープ', chunks: [{ t: 'We', r: 'S', e: '👧' }, { t: 'call', r: 'V', e: '🗣️' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'lunch', r: 'C', e: '🍱' }] },
      { jp: '私はその卵が新鮮だとわかる。', en: 'I find the eggs fresh.', dish: 'しんせんなたまご', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'find', r: 'V', e: '🔍' }, { t: 'the eggs', r: 'O', e: '🥚' }, { t: 'fresh', r: 'C', e: '🌿' }] },
      { jp: '彼はそのスープを辛いと感じる。', en: 'He finds the soup spicy.', dish: 'ピリからスープ', chunks: [{ t: 'He', r: 'S', e: '👦' }, { t: 'finds', r: 'V', e: '🔍' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'spicy', r: 'C', e: '🌶️' }] },
      { jp: '母はドアを開けたままにする。', en: 'My mother leaves the door open.', dish: 'あけっぱなしドア', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'leaves', r: 'V', e: '👋' }, { t: 'the door', r: 'O', e: '🚪' }, { t: 'open', r: 'C', e: '🔓' }] },
      { jp: '私たちは部屋をあたたかいままにする。', en: 'We leave the room warm.', dish: 'あたたかい部屋', chunks: [{ t: 'We', r: 'S', e: '👧' }, { t: 'leave', r: 'V', e: '👋' }, { t: 'the room', r: 'O', e: '🚪' }, { t: 'warm', r: 'C', e: '🌡️' }] },
      { jp: '彼女はケーキを新鮮に保つ。', en: 'She keeps the cake fresh.', dish: 'しんせんなケーキ', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the cake', r: 'O', e: '🍰' }, { t: 'fresh', r: 'C', e: '🌿' }] },
      { jp: '姉はスープを甘くする。', en: 'My sister makes the soup sweet.', dish: 'あまいスープ', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'sweet', r: 'C', e: '🍬' }] },
      { jp: '時間がパンを固くする。', en: 'Time makes the bread hard.', dish: 'かたいパン', chunks: [{ t: 'Time', r: 'S', e: '⏰' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the bread', r: 'O', e: '🍞' }, { t: 'hard', r: 'C', e: '🪨' }] },
      { jp: '兄はスープを熱く保つ。', en: 'My brother keeps the soup hot.', dish: 'あつあつコーンスープ', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'hot', r: 'C', e: '♨️' }] },
      { jp: '私はその魚が新鮮だとわかる。', en: 'I find the fish fresh.', dish: 'しんせんな魚', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'find', r: 'V', e: '🔍' }, { t: 'the fish', r: 'O', e: '🐟' }, { t: 'fresh', r: 'C', e: '🌿' }] },
      { jp: '彼らは部屋をきれいにする。', en: 'They make the room clean.', dish: 'きれいな部屋', chunks: [{ t: 'They', r: 'S', e: '👨‍👩‍👧' }, { t: 'make', r: 'V', e: '🔄' }, { t: 'the room', r: 'O', e: '🚪' }, { t: 'clean', r: 'C', e: '✨' }] },
    ],
  },
  {
    key: 'SVOCM',
    emoji: '🔥',
    name: '変化球メニュー＋：仕上げの一手間',
    pattern: 'S + V + O + C + M',
    desc: 'O＝Cの変化に、いつ・どこで(M)を添えて、シェフの技をもっと際立たせよう。',
    puzzles: [
      { jp: '母はいつも夕食後にキッチンをきれいにする。', en: 'My mother keeps the kitchen clean after dinner.', dish: 'ぴかぴかキッチン', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the kitchen', r: 'O', e: '🏠' }, { t: 'clean', r: 'C', e: '✨' }, { t: 'after dinner', r: 'M', e: '🌙' }] },
      { jp: '私は毎朝卵を新鮮に保つ。', en: 'I keep the eggs fresh every morning.', dish: 'あさのしんせんたまご', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'keep', r: 'V', e: '🔒' }, { t: 'the eggs', r: 'O', e: '🥚' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '母は10分でスープを熱くする。', en: 'My mother makes the soup hot in ten minutes.', dish: 'じゅっぷんスープ', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'hot', r: 'C', e: '♨️' }, { t: 'in ten minutes', r: 'M', e: '⏱️' }] },
      { jp: '私たちは放課後にキッチンをきれいに保つ。', en: 'We keep the kitchen clean after school.', dish: 'ほうかごキッチン', chunks: [{ t: 'We', r: 'S', e: '👧' }, { t: 'keep', r: 'V', e: '🔒' }, { t: 'the kitchen', r: 'O', e: '🏠' }, { t: 'clean', r: 'C', e: '✨' }, { t: 'after school', r: 'M', e: '🎒' }] },
      { jp: '兄は毎晩ドアを閉めたままにする。', en: 'My brother leaves the door closed every night.', dish: 'よるのとじたドア', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'leaves', r: 'V', e: '👋' }, { t: 'the door', r: 'O', e: '🚪' }, { t: 'closed', r: 'C', e: '🔒' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '太陽は毎日水をあたたかくする。', en: 'The sun makes the water warm every day.', dish: 'まいにちのおゆ', chunks: [{ t: 'The sun', r: 'S', e: '☀️' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the water', r: 'O', e: '💧' }, { t: 'warm', r: 'C', e: '🌡️' }, { t: 'every day', r: 'M', e: '📅' }] },
      { jp: '父はオーブンでパンを茶色にする。', en: 'My father makes the bread brown in the oven.', dish: 'オーブンパン', chunks: [{ t: 'My father', r: 'S', e: '👨' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the bread', r: 'O', e: '🍞' }, { t: 'brown', r: 'C', e: '🟤' }, { t: 'in the oven', r: 'M', e: '🔥' }] },
      { jp: '料理人はコンロでスープを熱くする。', en: 'The cook makes the soup hot on the stove.', dish: 'コンロスープ', chunks: [{ t: 'The cook', r: 'S', e: '👨‍🍳' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'hot', r: 'C', e: '♨️' }, { t: 'on the stove', r: 'M', e: '🍳' }] },
      { jp: '私は家で野菜を新鮮に保つ。', en: 'I keep the vegetables fresh at home.', dish: 'おうちの野菜', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'keep', r: 'V', e: '🔒' }, { t: 'the vegetables', r: 'O', e: '🥦' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'at home', r: 'M', e: '🏠' }] },
      { jp: '彼女はケーキをすぐに甘くする。', en: 'She makes the cake sweet quickly.', dish: 'すぐあまいケーキ', chunks: [{ t: 'She', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the cake', r: 'O', e: '🍰' }, { t: 'sweet', r: 'C', e: '🍬' }, { t: 'quickly', r: 'M', e: '⚡' }] },
      { jp: '私たちはパンを1時間やわらかく保つ。', en: 'We keep the bread soft for an hour.', dish: 'いちじかんパン', chunks: [{ t: 'We', r: 'S', e: '👧' }, { t: 'keep', r: 'V', e: '🔒' }, { t: 'the bread', r: 'O', e: '🍞' }, { t: 'soft', r: 'C', e: '☁️' }, { t: 'for an hour', r: 'M', e: '⏳' }] },
      { jp: '姉は夕食前にお茶を冷たくする。', en: 'My sister makes the tea cold before dinner.', dish: 'ゆうしょくまえのお茶', chunks: [{ t: 'My sister', r: 'S', e: '👧' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the tea', r: 'O', e: '🍵' }, { t: 'cold', r: 'C', e: '❄️' }, { t: 'before dinner', r: 'M', e: '🍽️' }] },
      { jp: '彼は毎朝その魚が新鮮だとわかる。', en: 'He finds the fish fresh every morning.', dish: 'あさのさかな', chunks: [{ t: 'He', r: 'S', e: '👦' }, { t: 'finds', r: 'V', e: '🔍' }, { t: 'the fish', r: 'O', e: '🐟' }, { t: 'fresh', r: 'C', e: '🌿' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '母は夕食後にドアを開けたままにする。', en: 'My mother leaves the door open after dinner.', dish: 'ゆうしょくごのドア', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'leaves', r: 'V', e: '👋' }, { t: 'the door', r: 'O', e: '🚪' }, { t: 'open', r: 'C', e: '🔓' }, { t: 'after dinner', r: 'M', e: '🌙' }] },
      { jp: '私は毎日部屋をきれいにする。', en: 'I make the room clean every day.', dish: 'まいにちのへや', chunks: [{ t: 'I', r: 'S', e: '🧑' }, { t: 'make', r: 'V', e: '🔄' }, { t: 'the room', r: 'O', e: '🚪' }, { t: 'clean', r: 'C', e: '✨' }, { t: 'every day', r: 'M', e: '📅' }] },
      { jp: '彼らは10分でカレーを辛くする。', en: 'They make the curry spicy in ten minutes.', dish: 'じゅっぷんカレー', chunks: [{ t: 'They', r: 'S', e: '👨‍👩‍👧' }, { t: 'make', r: 'V', e: '🔄' }, { t: 'the curry', r: 'O', e: '🍛' }, { t: 'spicy', r: 'C', e: '🌶️' }, { t: 'in ten minutes', r: 'M', e: '⏱️' }] },
      { jp: '冷蔵庫は毎晩お茶を冷たく保つ。', en: 'The refrigerator keeps the tea cold every night.', dish: 'よるのつめたいお茶', chunks: [{ t: 'The refrigerator', r: 'S', e: '🧊' }, { t: 'keeps', r: 'V', e: '🔒' }, { t: 'the tea', r: 'O', e: '🍵' }, { t: 'cold', r: 'C', e: '❄️' }, { t: 'every night', r: 'M', e: '🌙' }] },
      { jp: '弟はキッチンでスープを熱くする。', en: 'My brother makes the soup hot in the kitchen.', dish: 'だいどころスープ', chunks: [{ t: 'My brother', r: 'S', e: '👦' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the soup', r: 'O', e: '🍲' }, { t: 'hot', r: 'C', e: '♨️' }, { t: 'in the kitchen', r: 'M', e: '🏠' }] },
      { jp: '私たちは毎朝ミルクを冷たく保つ。', en: 'We keep the milk cold every morning.', dish: 'あさのつめたいミルク', chunks: [{ t: 'We', r: 'S', e: '👧' }, { t: 'keep', r: 'V', e: '🔒' }, { t: 'the milk', r: 'O', e: '🥛' }, { t: 'cold', r: 'C', e: '❄️' }, { t: 'every morning', r: 'M', e: '🌅' }] },
      { jp: '母は夕食前にキッチンをきれいにする。', en: 'My mother makes the kitchen clean before dinner.', dish: 'ゆうしょくまえのキッチン', chunks: [{ t: 'My mother', r: 'S', e: '👩' }, { t: 'makes', r: 'V', e: '🔄' }, { t: 'the kitchen', r: 'O', e: '🏠' }, { t: 'clean', r: 'C', e: '✨' }, { t: 'before dinner', r: 'M', e: '🍽️' }] },
    ],
  },
];
